import {
  Board20Regular,
  ArrowDownload20Regular,
  Delete20Regular,
  HandRight20Regular,
  Cursor20Regular,
  Sparkle20Regular,
  Dismiss20Regular,
  SpinnerIos20Regular,
  WeatherSunny20Regular,
  WeatherMoon20Regular,
  ChevronDown16Regular,
  DocumentText20Regular,
  DocumentJavascript20Regular,
  FolderZip20Regular,
  Video20Regular,
  Image20Regular,
  Globe16Regular,
  Settings20Regular,
  Person20Regular,
  SignOut20Regular,
} from '@ricons/fluent'
import type { IconRegistry } from './index'

export const fluentRegistry: IconRegistry = {
  board: Board20Regular,
  download: ArrowDownload20Regular,
  delete: Delete20Regular,
  hand: HandRight20Regular,
  cursor: Cursor20Regular,
  sparkle: Sparkle20Regular,
  dismiss: Dismiss20Regular,
  spinner: SpinnerIos20Regular,
  sun: WeatherSunny20Regular,
  moon: WeatherMoon20Regular,
  chevronDown: ChevronDown16Regular,
  documentText: DocumentText20Regular,
  documentCode: DocumentJavascript20Regular,
  folderZip: FolderZip20Regular,
  video: Video20Regular,
  image: Image20Regular,
  globe: Globe16Regular,
  settings: Settings20Regular,
  user: Person20Regular,
  signOut: SignOut20Regular,
}
